import React from "react";
import { useParams, Link } from "react-router-dom";
import { useGetSharedNarrativeQuery } from "@/store/api";
import { FileText, Clock, AlertTriangle } from "lucide-react";

export default function SharedNarrativePage() {
  const { token } = useParams<{ token: string }>();
  const { data: res, isLoading, error } = useGetSharedNarrativeQuery(token || "");

  if (isLoading) {
    return (
      <div className="w-full min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="w-8 h-8 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  if (error || !res?.success || !res.data) {
    return (
      <div className="w-full min-h-screen bg-slate-50 flex items-center justify-center p-6">
        <div className="max-w-md w-full bg-white border border-slate-200 shadow-sm rounded-2xl p-8 flex flex-col items-center text-center">
          <div className="w-12 h-12 bg-red-50 text-red-500 rounded-full flex items-center justify-center mb-4">
            <AlertTriangle size={20} />
          </div>
          <h2 className="text-lg font-bold text-slate-900 mb-2">Link Expired or Invalid</h2>
          <p className="text-sm text-slate-500 mb-6">This execution narrative link is no longer valid or has expired.</p>
          <Link to="/" className="text-sm font-semibold text-indigo-600 hover:text-indigo-700">Return to floework</Link>
        </div>
      </div>
    );
  }

  const narrative = res.data;

  return (
    <div className="w-full min-h-screen bg-slate-50 py-12 px-6">
      <div className="max-w-2xl mx-auto flex flex-col gap-6">
        
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-indigo-600 text-white font-bold rounded-xl flex items-center justify-center shadow-sm">
              {narrative.user.name.substring(0,2).toUpperCase()}
            </div>
            <div>
              <p className="text-sm font-bold text-slate-900">{narrative.user.name}</p>
              <p className="text-xs font-semibold text-slate-500 flex items-center gap-1.5">
                <FileText size={12} /> Effort Narrative
              </p>
            </div>
          </div>
          <p className="text-xs font-semibold text-slate-400 bg-white border border-slate-200 px-3 py-1.5 rounded-lg shadow-sm flex items-center gap-1.5">
            <Clock size={12} /> Week {narrative.weekLabel}
          </p>
        </div>

        <div className="bg-white border border-slate-200/80 rounded-2xl shadow-xl shadow-slate-200/40 p-8 min-h-[300px]">
          <p className="text-[15px] leading-relaxed text-slate-800 whitespace-pre-wrap">
            {narrative.body}
          </p>
        </div>
        
        <div className="flex justify-center mt-8">
           <Link to="/" className="text-xs font-semibold text-slate-400 hover:text-slate-600 transition-colors flex items-center gap-2">
             <div className="w-4 h-4 bg-indigo-500 rounded-sm"></div> Generated by floework
           </Link>
        </div>

      </div>
    </div>
  );
}
